### PR TITLE
fix(#193): only create indexes if table does not exist

### LINKED ISSUE #193: Creating indexes on startup of couch2pg causes locks in postgres
couch2pg attempts to create the couchdb table and indexes on saved_timestamp and deleted, using IF NOT EXISTS clauses to do nothing if the table and indexes are already created.

For `create table if not exists` this is fine, however for `create index if not exists`, postgres acquires a table lock BEFORE checking if the index already exists.
When dbt is running a long query against couch2pg, this means that the couch2pg script hangs.

couch2pg should only attempt to create indexes if the table did not exist

### PR DESCRIPTION
**Pull request by witash**
closes #193 

check if table exists in a separate query before creating indexes

### CODE REVIEW

File: couch2pg/src/setup.js [hunk 1]
```diff
@@ -25,12 +26,37 @@ const createTimestampIndex = `
...
   await client.query(createSchema);
-  await client.query(createTable);
-  await client.query(createDeleteIndex);
-  await client.query(createTimestampIndex);
+
+  // create the table and indexes if they don't exist
+  // note that `CREATE INDEX IF NOT EXISTS` acquires a lock
+  // even if the index exists, so cannot rely on it here,
+  // have to actually check if the table exists in a separate query
+  const tableExists = await checkTableExists(client);
```
Comment (dianabarsan) [inline couch2pg/src/setup.js:53]: Can return early here instead: 
```suggestion
if (await checkTableExists(client)) {
  return;
}
```

File: couch2pg/tests/unit/setup.spec.js [hunk 2]
```diff
@@ -13,6 +13,10 @@ describe('setup', () => {
       end: sinon.stub(),
     };
 
+    pgClient.query.withArgs(`SELECT 1 FROM v1.whatever LIMIT 1;`).rejects({
```
Comment (dianabarsan) [inline couch2pg/tests/unit/setup.spec.js:16]: Please add a unit test where the table already exists and doesn't get created on startup.

**Review by dianabarsan — CHANGES_REQUESTED** [review]
Sweet. One minor change + unit test request.

**Comment by witash** [comment]
looking a bit deeper into postgres locking and there's a simpler way to fix this; using `CREATE INDEX CONCURRENTLY IF NOT EXISTS` acquires a less restrictive lock ('SHARE UPDATE EXCLUSIVE') which doesn't conflict with the type of lock that inserts get ('ROW EXCLUSIVE').

**Review by dianabarsan — APPROVED** [review]
Thanks for spending extra time to read about how locks get triggered in PG! This is absolutely much better!
